=== amechkarova/XML/catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT catalog (regions, wineries, wines)>
<!ELEMENT regions (region+)>
<!ELEMENT wineries (winery+)>
<!ELEMENT wines (wine+)>
<!ELEMENT region (name)>
<!ELEMENT winery (name, year, vineyards, location, owner+, wine_maker+, brand+, branch*, annual_production?)>
<!ELEMENT wine (variety, year, colour, price, description)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT vineyards (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT owner (#PCDATA)>
<!ELEMENT wine_maker (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT branch (year, description)>
<!ELEMENT annual_production (#PCDATA)>
<!ELEMENT variety (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>


<!ATTLIST region
	id ID #REQUIRED
>
<!ATTLIST winery
	id ID #REQUIRED
	region_id IDREF #REQUIRED
	image ENTITY #REQUIRED
	logo ENTITY #REQUIRED
>
<!ATTLIST branch
	name CDATA #REQUIRED
	id ID #REQUIRED
	winery_id IDREF #FIXED "w03"
>
<!ATTLIST wine
	name CDATA #REQUIRED
	winery_id IDREFS #REQUIRED
	image ENTITY #REQUIRED
>




<!NOTATION JPG PUBLIC "jpg">
<!NOTATION PNG PUBLIC "PNG 1.0" "png">
<!NOTATION SVG PUBLIC "svg">

<!ENTITY karabunar_winery SYSTEM "http://www.bulgarianwine.net/sites/default/files/styles/bootstrap3_col11/public/Karabunar%20Winery.jpg?itok=iNF2RU66" 
NDATA JPG>
<!ENTITY karabunar_logo SYSTEM "http://www.bulgarianwine.net/sites/default/files/styles/bootstrap3_col12/public/Karabunar%20logo.jpg?itok=eIvTZLCq"
NDATA JPG>
<!ENTITY asenovgrad_winery SYSTEM "http://mavrud.com/sites/default/files/inline-images/winery1.jpg" NDATA JPG>
<!ENTITY asenovgrad_logo SYSTEM "http://mavrud.com/themes/wine/logo-bg.png" NDATA PNG>
<!ENTITY domaineBoyar_winery SYSTEM "http://rosewine-expo.com/wp-content/uploads/2016/04/Domaine-Boyar-logo.jpg" NDATA JPG>
<!ENTITY domaineBoyar_logo SYSTEM "http://domaineboyar.com/assets/images/logo.svg" NDATA SVG>
<!ENTITY midalidare_winery SYSTEM "http://midalidare.bg/slides/11.jpg" NDATA JPG>
<!ENTITY midalidare_logo SYSTEM "http://midalidare.bg/images/logo.png" NDATA PNG>
<!ENTITY angelEstate_winery SYSTEM "http://enosiasti.bg/resources/12_Angelus_Estate_Architecture.jpg" NDATA JPG>
<!ENTITY angelEstate_logo SYSTEM "http://www.divino.bg/sites/default/files/imagecache/tall_thumb/AE%20logo.png" NDATA PNG>
<!ENTITY logodaj_winery SYSTEM "http://www.logodajwinery.com/sites/default/files/gallery/logodaj-winery-20.jpg" NDATA JPG>
<!ENTITY logodaj_logo SYSTEM "http://www.logodajwinery.com/sites/all/themes/logodaj/images/logodaj-logo.png" NDATA PNG>
<!ENTITY melnik_winery SYSTEM "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Villa_melnik_winery.jpg/800px-Villa_melnik_winery.jpg" NDATA JPG>
<!ENTITY melnik_logo SYSTEM "http://wineanddrinks.eu/wp-content/uploads/2013/11/logogoldtransparent.png" NDATA PNG>
<!ENTITY sallaEstate_winery SYSTEM "http://www.bulgarianwine.net/sites/default/files/styles/bootstrap3_col11/public/Salla%20Estate%20Winery.jpg?itok=MbIUgfPM" NDATA JPG>
<!ENTITY sallaEstate_logo SYSTEM "http://vinoshop.bg/userfiles/brand/image_50b6186642202a864a0c66ffe4080623.jpg" NDATA JPG>
<!ENTITY BG_Heritage_Mavrud SYSTEM "https://bulgaarsetopwijnen.be/image/cache/catalog/fotoswijnen/Bulgarian%20Heritage%20Mavrud%202015-300x300.png" NDATA PNG>
<!ENTITY Karabunar_Cabernet SYSTEM "http://bulgarian-heritage.com/products/p29348/1_p29348.png" NDATA PNG>
<!ENTITY Via_Vinera SYSTEM "http://bulgarian-heritage.com/products/p35673/1_p35673.png" NDATA PNG>
<!ENTITY Ornament_Syrah SYSTEM "http://mavrud.com/sites/default/files/styles/product_page/public/products/Syrah.jpg?itok=3RF_gcLb" NDATA JPG>
<!ENTITY Reserve_Mavrud SYSTEM "http://mavrud.com/sites/default/files/styles/product_page/public/products/mavrud_0.jpg?itok=rfXNKnzm" NDATA JPG>
<!ENTITY RueRomance_SBlanc SYSTEM "http://www.novjivot.info/wp-content/uploads/2016/05/vino-4.jpg" NDATA JPG>
<!ENTITY Quantum_PNoir_Syrah SYSTEM "https://s.winestyle.ru/images_gen/61727/0_0_orig.jpg" NDATA JPG>
<!ENTITY Korten_Syrah SYSTEM "http://www.sid-shop.com/wp-content/uploads/2014/12/KORTEN-SYRAH.png" NDATA PNG>
<!ENTITY Midalidare_CS_Merlo_PVerdot SYSTEM "http://shop.midalidare.bg/cms/user/products/385/cover1.jpg" NDATA JPG>
<!ENTITY Calista_Chardonnay SYSTEM "http://shop.midalidare.bg/product_thumb_284_0.jpg" NDATA JPG>
<!ENTITY Sees_Rose SYSTEM "http://shop.midalidare.bg/product_thumb_383_0.jpg" NDATA JPG>
<!ENTITY Angel_GoldStallion SYSTEM "http://www.vinobg.com/images/Gold-Stallion-2013.jpg" NDATA JPG>
<!ENTITY Angel_Deneb SYSTEM "http://www.bestwine.bg/media/catalog/product/cache/2/image/650x/040ec09b1e35df139433887a97daa66f/d/e/deneb_cf.jpg" NDATA JPG>
<!ENTITY Angel_Rose SYSTEM "http://www.angelsestatebg.com/uploads/images/thumb_388fb50351e75ffe480e1ce14bbff983bde3058b.png" NDATA PNG>
<!ENTITY Cattleya_SB_Chardonnay SYSTEM "http://www.angelsestatebg.com/uploads/images/thumb_579acbd5a81b10af962f9cbfba8c6bb67a213c5d.png" NDATA PNG>
<!ENTITY Viognier SYSTEM "http://www.logodajwinery.com/sites/default/files/styles/wine-current/public/wines/logodajviognier2015.png?itok=q7ywu3bC" NDATA PNG>
<!ENTITY Melnishka_Loza SYSTEM "http://www.logodajwinery.com/sites/default/files/styles/wine-current/public/wines/shirokamelnishkaloza2_1.png?itok=bDhudqHr" NDATA PNG>
<!ENTITY Nobile_Rose SYSTEM "http://www.logodajwinery.com/sites/default/files/styles/wine-current/public/wines/nobilerose_1.png?itok=-wdkbxAM" NDATA PNG>
<!ENTITY Bijoux SYSTEM "http://www.logodajwinery.com/sites/default/files/styles/wine-current/public/wines/bijoux2014preview.png?itok=sLwCCRy0" NDATA PNG>
<!ENTITY Aplauz_Merlot SYSTEM "http://www.meik98wines.com/img/OBIAVI/BIG_IMG_135912606814568.jpg" NDATA JPG>
<!ENTITY Bergule_Cuvee SYSTEM "http://www.meik98wines.com/img/OBIAVI/BIG_IMG_145459833619886.jpg" NDATA JPG>
<!ENTITY Family_Tradition SYSTEM "http://villamelnik.com/wp-content/uploads/2016/02/family-tradition-melnik-2013.png" NDATA PNG>
<!ENTITY Young_Crazy SYSTEM "http://villamelnik.com/wp-content/uploads/2016/05/YoungCrazy-2016.jpg" NDATA JPG>
<!ENTITY Riesling_Barrel_Aged SYSTEM "https://salla.bg/wp-content/uploads/2017/05/SALLA-katalog-BG_EN2017-Riesling-Barrel-Aged.jpg" NDATA JPG>
<!ENTITY Chardonnay SYSTEM "https://salla.bg/images/vinapng/thumb3_chardonnay_2_size_2.png" NDATA PNG>

=== amechkarova/XML/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<?xml-stylesheet type="text/xsl" href="catalog.xsl"?>
<catalog>
	<regions>
		<region id="r01">
			<name>West Thracian Lowland</name>
		</region>
		<region id="r02">
			<name>East Thracian Lowland</name>
		</region>
		<region id="r03">
			<name>Struma valley</name>
		</region>
		<region id="r04">
			<name>North Black Sea region</name>
		</region>
	</regions>
	<wineries>
		<winery id="w01" region_id="r01" image="karabunar_winery" logo="karabunar_logo">
			<name>Karabunar Winery</name>
			<year>2008</year>
			<vineyards>40 hectares</vineyards>
			<location>Karabunar Village</location>
			<owner>Stoyan Zhelev</owner>
			<owner>Ivaylo Zheglov</owner>
			<wine_maker>Nadezhda Dulgherska</wine_maker>
			<brand>Bulgarian Heritage</brand>
			<annual_production>45 000 bottles</annual_production>
		</winery>
		<winery id="w02" region_id="r01" image="asenovgrad_winery" logo="asenovgrad_logo">
			<name>Asenovgrad Winery</name>
			<year>1947</year>
			<vineyards>200 hectares</vineyards>
			<location>Asenovgrad</location>
			<owner>Rosen Chatalbashev</owner>
			<wine_maker>Lalo Geshev</wine_maker>
			<brand>Ornament</brand>
			<brand>Mavrud Asenovgrad</brand>
			<brand>Mavrud Reserve</brand>
			<brand>Cabernet Sauvignon</brand>
			<brand>Merlo</brand>
			<brand>Merlo Reserve</brand>
			<brand>Monastery shushukane</brand>
			<annual_production>3 500 000 bottles</annual_production>
		</winery>
		<winery id="w03" region_id="r02" image="domaineBoyar_winery" logo="domaineBoyar_logo">
			<name>Domaine Boyar</name>
			<year>1991</year>
			<vineyards>200 hectares</vineyards>
			<location>Sliven</location>
			<owner>Santa Ana Ventures</owner>
			<wine_maker>Vladimir Vluchkov</wine_maker>
			<wine_maker>Kapka Georgieva</wine_maker>
			<wine_maker>Dimitar Panov</wine_maker>
			<wine_maker>Doychin Andreev</wine_maker>
			<brand>Quantum</brand>
			<brand>Boyar</brand>
			<brand>Ars Longa</brand>
			<brand>Chanson</brand>
			<brand>Code</brand>
			<brand>Marc Girardelli</brand>
			<brand>Next Twenty Years</brand>
			<brand>Domaine Boyar Platinum</brand>
			<brand>Solitaire</brand>
			<branch name="Blue Rocks" id="w001" winery_id="w03">
				<year>1999</year>
				<description>Winery "Blue Rocks" is situated next to the landmark - Blue Rocks, at the foot of Stara  Planina, which eventually became its name.
			The region of the Thracian Plain, where it is located, is famous for the production of high quality red wines.</description>
			</branch>
			<branch name="Korten" id="w002" winery_id="w03">
				<year>2003</year>
				<description>The little boutique winery "Korten" is located in the wine-growing region "Thracian Lowland". 
			It is known with the methods of micro-vinification and its emblematic red wines.</description>
			</branch>
			<annual_production>10 000 000 bottles</annual_production>
		</winery>
		<winery id="w04" region_id="r02" image="midalidare_winery" logo="midalidare_logo">
			<name>Midalidare Estate</name>
			<year>2009</year>
			<vineyards>165 hectares</vineyards>
			<location>Mogilovo Village</location>
			<owner>Yevgeny Yusupov</owner>
			<wine_maker>Alexander Aleksiev</wine_maker>
			<wine_maker>Nikolay Katerov</wine_maker>
			<brand>Midalidare</brand>
			<brand>Grand Vintage</brand>
			<brand>Carpe Diem</brand>
			<brand>Silver Angel</brand>
			<annual_production>330 000 bottles</annual_production>
		</winery>
		<winery id="w05" region_id="r02" image="angelEstate_winery" logo="angelEstate_logo">
			<name>Angel's Estate</name>
			<year>2008</year>
			<vineyards>106 hectares</vineyards>
			<location>Banya Village</location>
			<owner>Ivan Angelov</owner>
			<owner>Luka Angelov</owner>
			<wine_maker>Alexander Velyanov</wine_maker>
			<brand>Cattleya</brand>
			<brand>Stallion</brand>
			<brand>Angel</brand>
			<brand>Deneb</brand>
		</winery>
		<winery id="w06" region_id="r03" image="logodaj_winery" logo="logodaj_logo">
			<name>LOGODAJ Winery</name>
			<year>1994</year>
			<vineyards>650 hectares</vineyards>
			<location>Logodaj Village</location>
			<owner>Malin Shirokanski</owner>
			<owner>Nedyalko Levunliev</owner>
			<owner>Petar Drosanski</owner>
			<wine_maker>Svetlana Treneva</wine_maker>
			<brand>LOGODAJ</brand>
			<brand>Melnik</brand>
			<brand>Nobile</brand>
			<brand>Bijoux</brand>
		</winery>
		<winery id="w07" region_id="r03" image="melnik_winery" logo="melnik_logo">
			<name>Villa Melnik</name>
			<year>2013</year>
			<vineyards>30 hectares</vineyards>
			<location>Melnik City</location>
			<owner>Nikola Zikatanov</owner>
			<wine_maker>Rumyana Stoilova</wine_maker>
			<brand>Aplauz</brand>
			<brand>Bergule</brand>
			<brand>Family Tradition</brand>
			<brand>Young&amp;Crazy</brand>
		</winery>
		<winery id="w08" region_id="r04" image="sallaEstate_winery" logo="sallaEstate_logo">
			<name>Salla Estate</name>
			<year>2010</year>
			<vineyards>30 hectares</vineyards>
			<location>Blaskovo Village</location>
			<owner>Ivan Ivanov</owner>
			<wine_maker>Aneliya Hristakieva</wine_maker>
			<brand>Salla Estate</brand>
		</winery>
	</wineries>
	<wines>
		<wine name="Bulgarian Heritage Mavrud" winery_id="w01" image="BG_Heritage_Mavrud">
			<variety>Mavrud</variety>
			<year>2015</year>
			<colour>red</colour>
			<price>10 lv</price>
			<description>The wine has a dense violet colour. Intense young nose with abundant and juicy blackberry 
	fruit - blueberry, aronia. Medium long finish.</description>
		</wine>
		<wine name="Karabunar Contour Cabernet Sauvignon &amp; Pinot Noir" winery_id="w01" image="Karabunar_Cabernet">
			<variety>Cabernet Sauvignon</variety>
			<year>2016</year>
			<colour>red</colour>
			<price>10 lv</price>
			<description>
	The wine has a beautiful ruby ​​colour. A fresh nose with notes of raspberry, green leaves and pepper. 
	Tight, fresh and medium to tight with a slightly spicy finish.</description>
		</wine>
		<wine name="Via Vinera Chardonnay &amp; Sauvignon Blanc" winery_id="w01" image="Via_Vinera">
			<variety>Chardonnay &amp; Sauvignon Blanc</variety>
			<year>2016</year>
			<colour>white</colour>
			<price>16 lv</price>
			<description>This modern, recent Chardonnay blend and Sauvignon Blanc harmoniously combines the colourful and peach flavors 
	typical of Chardonnay with gooseberries, grapefruit on the one hand and the live lemon juice of Sauvignon on the other. The taste is soft, mature, 
	dense and complex with a wonderful citrus finish.</description>
		</wine>
		<wine name="Ornament Syrah Reserve" winery_id="w02" image="Ornament_Syrah">
			<variety>Syrah</variety>
			<year>2013</year>
			<colour>red</colour>
			<price>8 lv - 13.99 lv</price>
			<description>The wine is characterized by a ruby-red colour. The wine has a complex, captivating aroma of coffee 
	and black currant. Smooth body, harmonious taste and sweet finish.</description>
		</wine>
		<wine name="Reserve" winery_id="w02" image="Reserve_Mavrud">
			<variety>Mavrud</variety>
			<year>2013</year>
			<colour>red</colour>
			<price>7.45 lv</price>
			<description>It has a saturated ruby ​​red to red colour. Active nose - a combination of varietal flavor with the aromas of barley-derived carnation,
	lactone, vanilla and spices. The taste is tight, rounded with good length. The taste aroma is durable and impressive.</description>
		</wine>
		<wine name="Domaine Boyar Rue Romance Sauvignon Blanc" winery_id="w03" image="RueRomance_SBlanc">
			<variety>Sauvignon Blanc</variety>
			<year>2016</year>
			<colour>white</colour>
			<price>10 lv</price>
			<description>The wine is green in colour, bright and clear. Fresh and citrus-like nose with notes of grapefruit and 
	gooseberry. Light to medium body, harmonious and enjoyable to the finish.</description>
		</wine>
		<wine name="Domaine Boyar Quantum Rose Pinot Noir &amp; Syrah" winery_id="w03" image="Quantum_PNoir_Syrah">
			<variety>Sauvignon Blanc</variety>
			<year>2016</year>
			<colour>white</colour>
			<price>9 lv</price>
			<description>The wine has a sparkling colour - pale pink with gentle orange shades. The nose is intense with notes of 
	strawberry jam and cotton candy. A fresh, light body with a harmonious finish.</description>
		</wine>
		<wine name="Korten Syrah" winery_id="w03 w002" image="Korten_Syrah">
			<variety>Syrah</variety>
			<year>2016</year>
			<colour>red</colour>
			<price>20 lv</price>
			<description>The wine has a dense, purple colour. The nose is juicy, mature, attractive and smoky with notes of smoke and meat, sweet spices, baked prunes in chocolate and warm earthly shades. 
	Medium as a structure, flexible and juicy in the mouth with very well matured tannins and a long, fruity and sweet finish.</description>
		</wine>
		<wine name="Midalidare Mogilovo Village Cabernet Sauvignon &amp; Merlot &amp; Petit Verdot" winery_id="w04" image="Midalidare_CS_Merlo_PVerdot">
			<variety>Cabernet Sauvignon &amp; Merlot &amp; Petit Verdot</variety>
			<year>2015</year>
			<colour>red</colour>
			<price>20 lv</price>
			<description>The wine has a rich, dense purple colour. Attractive nose with notes of lime colour, vanilla, coffee and 
	cherry liqueur. Medium body, crisp and harmonious with still dominating oak accents in taste that remain in the finish.
	Attractive wine that can be drunk at the moment, but can also mature.</description>
		</wine>
		<wine name="Midalidare Calista Mogilovo Single Vineyard Chardonnay" winery_id="w04" image="Calista_Chardonnay">
			<variety>Chardonnay</variety>
			<year>2015</year>
			<colour>white</colour>
			<price>30 lv</price>
			<description>The wine has a rich golden colour with preserved fresh green glow. The nose is intense with notes of coffee,
